# --- Discord ---
bot_token: null
client_id: "${DISCORD_CLIENT_ID}"
status_message: "DM IA West Marches | /model"
allow_dms: false

permissions:
  users:
    admin_ids: []        # <<< clé OBLIGATOIRE
    allowed_ids: []
    blocked_ids: []
  roles:
    allowed_ids: []
    blocked_ids: []
  channels:
    allowed_ids: []
    blocked_ids: []

providers:
  groq:
    base_url: "https://api.groq.com/openai/v1"
    api_key: "${GROQ_API_KEY}"

models:
  groq/llama-3.1-8b-instant:
    temperature: 0.7
    top_p: 0.9
    max_tokens: 1024

system_prompt: |
  Tu es le DM IA d’un West Marches PbP D&D 5e.
  - Cadre la scène, pose les enjeux, propose au plus 3 actions.
  - Les JETS et RÈGLES sont gérés par Avrae (ne lance PAS les dés).
  - Quand un jet est requis, suggère une commande Avrae (ex. `!check perception`, `!check survival`, `!init`).
  - Après qu’un joueur poste le résultat Avrae, décris brièvement la conséquence.
  - Style: court, clair, FR (2–5 phrases).

max_messages: 25
use_plain_responses: false
