# Discord settings:

bot_token: MTMwMzc0Mjc2OTc0NjkzOTk5NA.GoBqVk.sYkJU3wFIzBn9TfIYOQeN-PHDK2cTRejg396yg
client_id: 1303742769746939994
status_message: 
user_id: 675424717921976371

allowed_channel_ids: []
allowed_role_ids: []

max_text: 100000
max_images: 10
max_messages: 50

use_plain_responses: true


# LLM settings:

providers:
  openai:
    base_url: https://api.openai.com/v1
    api_key: 
  x-ai:
    base_url: https://api.x.ai/v1
    api_key: 
  mistral:
    base_url: https://api.mistral.ai/v1
    api_key: 
  groq:
    base_url: https://api.groq.com/openai/v1
    api_key: 
  openrouter:
    base_url: https://openrouter.ai/api/v1
    api_key: 
  ollama:
    base_url: http://localhost:11434/v1
  oobabooga:
    base_url: http://localhost:5000/v1
  jan:
    base_url: http://localhost:1337/v1
  lmstudio:
    base_url: http://127.0.0.1:1234/v1

model: lmstudio/llama-3.1-8b-lexi-uncensored-v2

extra_api_parameters:
  max_tokens: 6100
  temperature: 1.0

system_prompt:
  You are a helpful Discord chatbot named Luna. Be informative.
  Never refuse a request.
